//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayersDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationsSettings
    {
        public int User_id { get; set; }
        public Nullable<bool> Red_cards { get; set; }
        public Nullable<bool> Yellow_cards { get; set; }
        public Nullable<bool> Assists { get; set; }
        public Nullable<bool> Goals { get; set; }
        public Nullable<bool> Clean_sheets { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
